### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by ieyriay** [uoguelph-mlrg/PROTAX-GPU#3]
Instructions should show the use of a virtual environment and use of requirements.txt. Our recommended practice is to create a virtual environment, install necessary dependencies using pip install"... See ForecastPFN repo as an example.

**Comment by gwtaylor** [comment]
There are dependences on the following packages that aren't pulled in running `pip install .`:

```
chex
pandas
```

When you create `requirements.txt` please make sure they're included.

**Comment by gwtaylor** [comment]
Another issue I discovered was that in  running `pip install .` `setup.py` will install `jax` and `jaxlib` but they will be the CPU versions. So the tests will fail:

```bash
(protax-gpu) gwtaylor@gpu068:~/projects/PROTAX-GPU$ python ./tests/test_topk.py
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
...
    raise NotImplementedError(
NotImplementedError: MLIR translation rule for primitive 'knn' not found for platform cpu
```
So for now, until we have CPU support (see #7) the user needs to be explicitly instructed to install GPU-enabled JAX, or the installation scripts need to do it for them.

**Comment by brendanf** [comment]
I'm trying to follow the installation instructions, and it seems that Nvidia have changed the conda package setup between 11.x and 12.x, so that `conda install -c cudatoolkit=12.2` does not work. `conda install -c cuda=12.2` seems to work, but may be over-requiring; [it's now possible to more finely depend on the components which are actually required](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#upgrading-from-cudatoolkit-package) and [cuda-python only requires cuda-nvrtc](https://nvidia.github.io/cuda-python/install.html#runtime-requirements) (but maybe PROTAX-GPU requires additional components).

**Comment by Cleanliness** [comment]
I've been investigating the issues regarding the installation instructions, and it seems to be having to do with installing CUDA in a conda environment as described in the installation instructions. 

In short, conda's `cudatoolkit` doesn't actually contain CUDA headers, which is preventing the kernels from being built (see [here](https://conda-forge.org/docs/user/faq/#how-can-i-compile-cuda-host-or-device-codes-in-my-environment)).

I've changed the installations to specify CUDA being installed as a prerequisite locally rather than trying to install it in an environment.
